# Site settings
title:       Rich Knight
email:       hi@rich-knight.com
author:      Rich Knight"
description: ""
baseurl:     ""
url:         "http://rich-knight.com"

# Google analytics
google_analytics: "UA-38039875-1"

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: rcknight
stackoverflow_id:
twitter_username: rcknight
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
sass:
  compressed: true

collections:
- projects